### ISSUE TITLE
Conda environments disappear

### ISSUE THREAD

**Issue by sashakames** [esgf-nimbus/getting_started#15]
My session timed out overnight and conda environments I created are now gone.

**Comment by sashakames** [comment]
Moreover, can one create an environment and then use with with a notebook or iPython window?

**Comment by jasonb5** [comment]
@sashakames

All environments should be persisted between sessions. If they disappear it's likely the `~/.condarc` config got overwritten. Check `~/.condarc` the contents should look like this
```shell
envs_dirs:
 - /home/jovyan/conda-envs
```
If you're using a custom condarc then add the section above and all subsequent environments should persist.

To use a conda environment as a notebook kernel you should just need to install `ipykernel` in the conda environment then refresh the page. After this the conda environment should show up in the `Launcher` page and kernel selection dropdown. If it still doesn't show up run `python -m ipykernel install --user --name <name>` in the conda environment. There's a section in the `getting_started.ipynb` called `JupyterLab and Conda` that covers this. It's in need of a updating though.

**Comment by sashakames** [comment]
Thanks @jasonb5 
 No .condarc for me.  So,  I'll create one and create a new env (easy enough) with ipykernel.  I suspected this was the sort of "basic" functionality we would want.

**Comment by sashakames** [comment]
Another question @jasonb5 - should we be able to setup.py install a package into a custom env and use that with the notebook?  so far doesn't work, but perhaps I need to re-init somehow?

**Comment by jasonb5** [comment]
@sashakames 
I see what happened, at some point i disabled writing the default `condarc`. I'll re-enable this, going forward that file will be written if not already present. I'll add an entry to the FAQ dealing with this.

It should work, in the terminal you need to activate the conda environment before running setup.py.

**Comment by sashakames** [comment]
It worked this time around.  I closed and reopened the browser tab.  That restored all my jupyter tabs (have several files open).

**Comment by jasonb5** [comment]
Closing this issue as i've added an entry into the FAQ.
