### ISSUE TITLE
git error message starting development image

### ISSUE THREAD

**Issue by sashakames** [esgf-nimbus/getting_started#17]
I thought to try the development image as it might have several preloaded tools so I don't have to start from scratch each time, including git:

Failed to load the jupyterlab-git server extensiongit command not found - please ensure you have Git > 2 installed

**Comment by jasonb5** [comment]
@sashakames I've disabled the JupyterLab-git extension as we've updated to 3.0.0 and there's an issue with a dependency of the extension that hasn't been updated.

**Comment by jasonb5** [comment]
I've added the git tool and is available in all images. Once the JupyterLab git extension is updated i'll add it back to the dev image.

For now let's close you this issue.
