### ISSUE TITLE
Invalid Password?

### ISSUE THREAD

**Issue by TonyB9000** [esgf-nimbus/getting_started#18]
The "login to nimbus" prompts me with "username or email" and "password".  As we are authenticating with github, I supplied my github username and password (the same one I just now entered to access this very "issues" page.  But it replies with "Invalid username or password.

**Comment by jasonb5** [comment]
@TonyB9000 
I'm guessing you're running into the issue on this page (https://github.com/esgf-compute/getting_started/blob/master/img/idp.png)? You need to select the `GitHub` button (circled in red) then log in with your Github credentials.

**Comment by TonyB9000** [comment]
Thanks Jason!
