### ISSUE TITLE
Missing basic utilities

### ISSUE THREAD

**Issue by jasonb5** [esgf-nimbus/getting_started#20]
- git
- less
- vi
- vim
- unzip
- scp
- rsync

**Comment by sashakames** [comment]
Also "vi" used by git for commit comments

**Comment by pochedls** [comment]
This is timely - I was just about to request that `git` be added.

**Comment by pochedls** [comment]
Can we add `unzip` to the list (this was going to be my workaround for not having git)?

**Comment by pochedls** [comment]
And `scp`

**Comment by jasonb5** [comment]
@sashakames @pochedls This has been updated in the latest images; base, dev and cdat. If you stopand restart your environments and you'll have access to these tools. The only image that will not have these changes is VCDAT image as this is managed by Carlos. 

Once it's verified these tools are available, we'll close this issue.

**Comment by pochedls** [comment]
This is working for me (including `ssh-keygen` to get git working). Thanks!
